name: macos-x64

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos-x64:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        run: |
          git clone https://github.com/google/angle .
      - name: Fetch depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Build
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          python scripts/bootstrap.py
          gclient sync
          gn gen out/Release --args="is_debug=false target_cpu=\"x64\" build_angle_deqp_tests=false"
          autoninja -C out/Release
      - name: Pack
        run: |
          mkdir angle-macos-x64
          mkdir angle-macos-x64/dist
          rm -rf out/Release/gen
          rm -rf out/Release/obj
          mv -f out/Release/* angle-macos-x64/dist/
          cp -rf include angle-macos-x64/
          find angle-macos-x64 -name ".clang-format" -delete
          find angle-macos-x64 -name "*.md" -delete
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: angle-macos-x64
          path: angle-macos-x64
