name: Builds

on:
  workflow_dispatch

jobs:
  build-darwin:
    runs-on: macOS-latest
    steps:
      - name: Checkout depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          
      - name: Checkout sources
        run: |
          git clone https://github.com/google/angle
      
      - name: Build
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          cd angle
          python scripts/bootstrap.py
          gclient sync
          git checkout master
          gn gen out/Release
          gn args out/Release --list=is_debug --args="is_debug=false"
          # autoninja -C out/Release
          cd ..
          mkdir angle_darwin
          mkdir angle_darwin/lib
          cp -f angle/out/Release/libEGL.dylib angle_darwin/lib/
          cp -f angle/out/Release/libGLESv1_CM.dylib angle_darwin/lib/
          cp -f angle/out/Release/libGLESv2.dylib angle_darwin/lib/
          cp -rf angle/include angle_darwin/
          find angle_darwin -name ".clang-format" -delete
          find angle_darwin -name "*.md" -delete
      -   name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: angle_darwin
            path: angle_darwin
