name: test-win

on: 
  workflow_dispatch

jobs:
  build-windows-x64-d3d11:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        run: |
          git clone https://github.com/google/angle .
      - name: Fetch depot_tools
        shell: bash
        run: |
          curl -ksS https://storage.googleapis.com/chrome-infra/depot_tools.zip > depot_tools.zip
          mkdir depot_tools
          unzip -q -o depot_tools.zip -d depot_tools
          rm -f depot_tools.zip
      - name: Build
        shell: cmd
        run: |
          set PATH=%cd%\depot_tools;%PATH%
          set DEPOT_TOOLS_WIN_TOOLCHAIN=0
          set vs2019_install=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
          set WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10
          cmd /c gclient
          cmd /c python scripts/bootstrap.py
          cmd /c gclient sync
          cmd /c gn gen out/Release
          cmd /c gn args out/Release --list --short --args="is_debug=false target_cpu=\"x64\" build_angle_deqp_tests=false"
          echo %PATH%
          dir %cd%\depot_tools
          cmd /c autoninja -C out/Release
      - name: Pack
        shell: bash
        run: |
          dir out\Release
          mkdir angle-windows-x64-d3d11
          mkdir angle-windows-x64-d3d11/lib
          cp -f out/Release/libEGL.dll angle-windows-x64-d3d11/lib/
          cp -f out/Release/libEGL.dll.lib angle-windows-x64-d3d11/lib/libEGL.lib
          cp -f out/Release/libGLESv1_CM.dll angle-windows-x64-d3d11/lib/
          cp -f out/Release/libGLESv1_CM.dll.lib angle-windows-x64-d3d11/lib/libGLESv1_CM.lib
          cp -f out/Release/libGLESv2.dll angle-windows-x64-d3d11/lib/
          cp -f out/Release/libGLESv2.dll.lib angle-windows-x64-d3d11/lib/libGLESv2.lib
          cp -rf include angle-windows-x64-d3d11/
          find angle-windows-x64-d3d11 -name ".clang-format" -delete
          find angle-windows-x64-d3d11 -name "*.md" -delete
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: angle-windows-x64-d3d11
          path: angle-windows-x64-d3d11
